### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by Blaze-Lua** [jeffshee/gnome-ext-hanabi#14] opened 2022-08-17 10:35 UTC
the wallpaper does not show, here is the log
Timelines with detached actors are not supported. <unnamed>[<Preview>:0x55d22c82da60] in animation of duration 250ms but not on stage.
Timelines with detached actors are not supported. <unnamed>[<Preview>:0x55d22c82dda0] in animation of duration 250ms but not on stage.
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
Hanabi: codepath = /home/hikari/.local/share/gnome-shell/extensions/hanabi-extension@jeffshee.github.io
Hanabi: filepath = /home/hikari/.local/share/gnome-shell/extensions/hanabi-extension@jeffshee.github.io/video.mp4
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
[Hanabi], renderer == null || useDummyWallpaper == true
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
[Hanabi], _updateWallpaper: [0x55d22c28e590 ClutterClone]
clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (self)' failed
[Hanabi], _updateWallpaper: [0x55d22c28e8d0 ClutterClone]
[Hanabi], _updateWallpaper: [0x55d22c82cd60 ClutterClone]
[Hanabi], _updateWallpaper: [0x55d22eceed70 ClutterClone]
[Hanabi], _updateWallpaper: [0x55d22ecee3b0 ClutterClone]
clutter_actor_remove_child: assertion 'child->priv->parent == self' failed
clutter_actor_remove_child: assertion 'child->priv->parent == self' failed
clutter_actor_remove_child: assertion 'child->priv->parent == self' failed
clutter_actor_remove_child: assertion 'child->priv->parent == self' failed

**Comment by jeffshee** [comment] 2022-08-21 05:52
Closed. Possible duplicate of #13

**Closed by jeffshee** 2022-08-21 05:52 UTC
