### ISSUE TITLE
Automatically pause video on battery.

### ISSUE THREAD

**Issue by 18aKissD** [jeffshee/gnome-ext-hanabi#94] opened 2023-11-20 12:31 UTC
**Description**
My problem is if I have programs open while on battery and can't see the video, it drains my battery quite badly (8->15w). So I am suggesting to include a feature where you can check to automatically pause video when starting from battery.

**OS and Shell Information**
(X11/Wayland).
 - OS: [Ubuntu 22.04]
 - GNOME Shell: [42]
 - Session type: [Wayland]

**Additional Information**
Maybe you can include a battery saver, which means if the charger is unplugged and laptop is on battery, it pauses automatically. Though, this should be optional (I mean checkable) so that different users with different laptops can check if they want it or not.

**Comment by neuralnermal** [comment] 2023-12-08 00:14
Came to suggest something like this. Currently at 89% of battery left, it said it has about a little less than 2 hours of battery life. After turning hanabi off, it now says I have 4 hours and 42 minutes of battery life.

**Comment by ThomasHineXYZ** [comment] 2024-01-10 01:25
This would be a great feature.

**Comment by kernelb00t** [comment] 2024-01-27 09:15
Duplicate of #20. Keep in mind to check if your issue already exists before posting 😉

**Closed** 2024-05-25 09:49 UTC
Labels: enhancement
