### ISSUE TITLE
Clicking on the desktop wallpaper hides the dash to panel

### ISSUE THREAD

**Issue by enamul6m** [jeffshee/gnome-ext-hanabi#65] opened 2023-06-28 12:26 UTC
**Description**
After the computer starts clicking on the desktop wallpaper hides the dash to panel(both left and right click). When I disable and re-enabled the extension it fixes. So I tried "/usr/bin/gnome-extensions disable hanabi-extension@jeffshee.github.io && /usr/bin/gnome-extensions enable hanabi-extension@jeffshee.github.io" command on "Startup Applications" but that didn't work. It works in the terminal though. I don't know what to do. I am a newbie to the Linux environment.

**OS and Shell Information**
 - OS: Ubuntu 23.04
 - GNOME Shell: 44.2
 - Session type: Wayland

**Comment by jeffshee** [comment] 2023-07-09 06:16
Hi @enamul6m, thanks for reporting.

Yes, I can confirm this issue. The cause of this is unknown, but I've found that switching the workspace can temporarily fix this issue without having to re-enabling Hanabi for each shell restart. I had included this workaround to the README troubleshooting section.

Sadly, I still couldn't find a fix for this at the moment. 😫

**Closed** 2023-08-26 07:23 UTC
Labels: bug
