### ISSUE TITLE
Right click stop working 

### ISSUE THREAD

**Issue by johan-sorman** [jeffshee/gnome-ext-hanabi#8] opened 2022-07-29 14:31 UTC
Maybe you’re already aware, but I noticed after enable the extension my right clicking stopped working on various applications. Only seemed to work on desktop. Disable the extension and it works again.

CPU: Ryzen 5950X
GPU: RTX 3090 with latest drivers 
RAM: 32gb 

aside of that, it looks great.

**Comment by Tarch1** [comment] 2022-07-30 18:22
Same issue as mine #4

**Comment by jeffshee** [comment] 2022-07-31 10:21
@johan-sorman Hi, thanks for reporting.

Could this be the same issue as the #7? Like the (right click) context menu doesn't show up?
If that is the case, I just pushed a fix that probably can fix yours too. 
Please try the master and see if the issue is gone or not.

@Tarch1 Since you mentioned that this issue is the same as yours, could you please also check the latest master?

Thanks~ 😎

**Comment by johan-sorman** [comment] 2022-07-31 10:35
@jeffshee i believe so, i Will try out the updated master

**Comment by Tarch1** [comment] 2022-08-03 16:21
For me now works perfectly, thanks

**Comment by jeffshee** [comment] 2022-08-27 01:35
Closed as fixed.

**Closed by jeffshee** 2022-08-27 01:35 UTC
Labels: bug
