### ISSUE TITLE
Unusable with two screens in gnome 43

### ISSUE THREAD

**Issue by Seikm** [jeffshee/gnome-ext-hanabi#25] opened 2022-11-22 19:09 UTC
Various rendering and performance bugs in gnome 43 using two screens.

I have clapper installed by the opensuse package manager, but it seems that the extension cannot use it.
Second screen totally buggy, wallpaper covers the topbar in the main workspace, and other bugs.

I recorded two videos showing all the bugs, the first video has other extensions enabled and the second video is without extensions and shows the logs.

[video with extensions (link to download)](https://cdn.discordapp.com/attachments/887435656312283166/1044689622510346240/with_extensions.mp4)
[video without extensions (link to download)](https://cdn.discordapp.com/attachments/887435656312283166/1044689641594429450/no_extensions.mp4)

**Comment by delucca** [comment] 2022-11-22 19:13
Same thing here. Also, if I press Super+D it breaks the wallpaper on the secondary screen. The same happens if I try to switch to a secondary workspace (the wallpaper breaks

**Comment by Rafostar** [comment] 2022-11-24 10:48
> I have clapper installed by the opensuse package manager, but it seems that the extension cannot use it.

Extension uses `GstPlay` library (including its GI bindings) together with custom sinks. Check if you have installed both:
```sh
gst-inspect-1.0 clappersink
gjs -c "let GstPlay = imports.gi.GstPlay;"
```

If you are correctly using a custom sink, `test-renderer.sh` window title will have suffix with the sink name, e.g: `- clappersink`.

**Comment by Seikm** [comment] 2022-11-24 16:59
@Rafostar 
The introspection bindings were missing, I downloaded them and now `test-renderer.sh` runs with clappersink.
But when I run `gst-inspect-1.0 clappersink` in the terminal, the response is still `No such element or plugin 'clappersink'`. I tried downloading the 32bit versions of gstplay and gstplayer, but the response remains the same.
Performance improved from 15% CPU to 7%. So I don't know if this is an issue that should be ignored, or maybe the performance could be further improved?

**Comment by Rafostar** [comment] 2022-11-24 18:17
@Seikm 
>  in the terminal, the response is still No such element or plugin 'clappersink'

Either packaging problem or some broken plugin cache. Definitely not hanabi fault. If it works from inside the code, I guess you can ignore it. Regarding performance, I do not want to start discussing about this in the same issue without the extension dev permission. For Clapper related questions feel free to ask on Clapper matrix channel through. Let's not change this issue original topic.

**Comment by delucca** [comment] 2022-11-24 18:38
@Rafostar one question, what about what I reported? I can record a video if you want, but basically everytime I press Super+D (or basically any key if the desktop is visible) the wallpaper crashes (it simply duplicates in a super weird alignment

The same happens if I try switching workspaces

**Comment by Rafostar** [comment] 2022-11-24 18:56
@delucca 
I only maintain/help with Clapper. You will have to wait for this extension developer response for anything extension related. Sorry.

**Comment by jeffshee** [comment] 2022-11-25 16:55
Hi @Seikm @delucca, thanks for reporting! Also @Rafostar thanks for helping~

@delucca May I know what's the action bind to the Super+D key combination? (I don't have this key combination enabled by default on Fedora, so I have no idea what it does.)

@Seikm Ok... It seems that I also have the same issue with dual screen setup in GNOME 42.4 as well. It could be a regression of previous commit. Let me check what caused this.

For the GNOME 43 support, please give me more times! 😂

As for performance, if hanabi uses clappersink for the playback, it's already doing its best! =)
There could be a minor CPU overhead on extension side (not on clapper side), since hanabi creates a new renderer's window preview and pastes it everywhere the system wallpaper appears. There may be a better and more efficient way to do it, but I'm out of ideas and know-how right now.

**(Off topic)** Below is some implementation details in case anyone is interested. Please open another issue for suggestions on this if any.

https://github.com/jeffshee/gnome-ext-hanabi/blob/f81b76cd0f62c34975746ac31b040bc965218e7f/src/gnomeShellOverride.js#L138-L147

As you can see I'm _abusing_ the `Shell.WindowPreviewLayout()` here for getting a clutter actor (in this case the renderer's window preview). Originally I wished I could use something like _ClutterGst_, that can play a video into a clutter actor, but that stuff is deprecated and doesn't work with GNOME Shell anymore... 😩

**Comment by Rafostar** [comment] 2022-11-25 17:06
@jeffshee 
> As for performance, if hanabi uses clappersink for the playback, it's already doing its best! =)

That might be true in case of Nvidia, but for Intel/AMD as I mentioned in https://github.com/jeffshee/gnome-ext-hanabi/pull/19#issue-1372884581, either you or users would have to install and enable newer experimental VA element under Wayland session to get current "best" =)

**Comment by delucca** [comment] 2022-11-25 17:18
> Hi @Seikm @delucca, thanks for reporting! Also @Rafostar thanks for helping~
> 
> @delucca May I know what's the action bind to the Super+D key combination? (I don't have this key combination enabled by default on Fedora, so I have no idea what it does.)
> 
> @Seikm Ok... It seems that I also have the same issue with dual screen setup in GNOME 42.4 as well. It could be a regression of previous commit. Let me check what caused this.
> 
> For the GNOME 43 support, please give me more times! joy
> 
> As for performance, if hanabi uses clappersink for the playback, it's already doing its best! =) There could be a minor CPU overhead on extension side (not on clapper side), since hanabi creates a new renderer's window preview and pastes it everywhere the system wallpaper appears. There may be a better and more efficient way to do it, but I'm out of ideas and know-how right now.
> 
> **(Off topic)** Below is some implementation details in case anyone is interested. Please open another issue for suggestions on this if any.
> 
> https://github.com/jeffshee/gnome-ext-hanabi/blob/f81b76cd0f62c34975746ac31b040bc965218e7f/src/gnomeShellOverride.js#L138-L147
> 
> As you can see I'm _abusing_ the `Shell.WindowPreviewLayout()` here for getting a clutter actor (in this case the renderer's window preview). Originally I wished I could use something like _ClutterGst_, that can play a video into a clutter actor, but that stuff is deprecated and doesn't work with GNOME Shell anymore... weary

about the Super+D, it is the combination to show the desktop. But, TBH, any keystroke I press glitches the wallpaper for some reason.

I can see the glitch after pressing Super+D probably because the wallpaper appears

**Comment by jeffshee** [comment] 2022-12-24 10:04
It is fixed in the latest commit! Sorry for the late and Merry Christmas~🎄

**Closed by jeffshee** 2022-12-24 10:04 UTC
Labels: bug, gnome 43
